workflows:
  ios-development:
    name: VisionClaw iOS (Development)
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "samples/CameraAccess/CameraAccess.xcodeproj"
        XCODE_SCHEME: "CameraAccess"
    scripts:
      - name: Build unsigned IPA
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
          mkdir -p build/ipa/Payload
          cp -r build/Build/Products/Debug-iphoneos/CameraAccess.app build/ipa/Payload/
          cd build/ipa && zip -r VisionClaw.ipa Payload/
    artifacts:
      - build/ipa/VisionClaw.ipa
